# Settings for the app
app:
  # HTML Title
  title: Safer Salem
  # Header name
  name: Safe Routes to School & Play
  # Meta description that will show up in Google search results
  meta_description: _(Safe Routes to School & Play in Salem, MA.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 42.51954
      lng: -70.8967155
    zoom: 16
    minZoom: 14
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-5f9w3eg9/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Autos:
    label: _(Auto Traffic issue)
    rules:
      - condition: '"{{location_type}}" === "Autos"'
        icon:
          iconUrl: /static/css/images/markers/dot-70d52c.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-70d52c.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  Pedestrians:
    label: _(Pedestrian traffic issue)
    rules:
      - condition: '"{{location_type}}" === "Pedestrians"'
        icon:
          iconUrl: /static/css/images/markers/dot-2654d2.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-2654d2.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  Bikes:
    label: _(Bike traffic issue)
    rules:
      - condition: '"{{location_type}}" === "Bikes"'
        icon:
          iconUrl: /static/css/images/markers/dot-dbcf2c.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-dbcf2c.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  PublicSpace:
    label: _(Public Space issue)
    rules:
      - condition: '"{{location_type}}" === "PublicSpace"'
        icon:
          iconUrl: /static/css/images/markers/dot-e1264d.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-e1264d.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Identify a problem)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Display as a list)
  show_map_button_label: _(Display as a map)
  action_text: _(identified)
  title: _(Tell us more...)
  anonymous_name: _(Someone)
  submit_button_label: _(Add to map)
  items:
    - prompt: Your name (optional, will be shown on the map)
      type: text
      name: submitter_name
      attrs:
        - key: size
          value: 30
    - prompt: "Type of problem"
      type: select
      options:
        - label: _(Please choose a category)
          value: ""
        - label: _(Auto Traffic issues)
          value: "Autos"
        - label: _(Pedestrian Traffic issues)
          value: "Pedestrians"
        - label: _(Bike Traffic issues)
          value: "Bikes"
        - label: _(Public Space)
          value: "PublicSpace"          
      name: location_type
      
    # Pedestrian traffic checkboxes
    - prompt: Uneven or indirect path
      type: checkbox
      name: pedestrian1
      attrs:
        - key: value
          value: Uneven or indirect path
    - prompt: Sidewalk too narrow or missing
      type: checkbox
      name: pedestrian2
      attrs:
        - key: value
          value: Sidewalk too narrow or missing
    - prompt: Intersection or crossing issue
      type: checkbox
      name: pedestrian3
      attrs:
        - key: value
          value: Intersection or crossing issue
    - prompt: Other
      type: checkbox
      name: pedestrian4
      attrs:
        - key: value
          value: Other

    # traffic issues
    - prompt: Speeding
      type: checkbox
      name: traffic1
      attrs:
        - key: value
          value: Speeding
    - prompt: Confusing intersection
      type: checkbox
      name: traffic2
      attrs:
        - key: value
          value: Confusing intersection
    - prompt: Cut-through vehicles
      type: checkbox
      name: traffic3
      attrs:
        - key: value
          value: Cut-through vehicles
    - prompt: Other (please explain)
      type: checkbox
      name: traffic4
      attrs:
        - key: value
          value: Other (please explain)

    # bike issues
    - prompt: Obstacle or hazard in path
      type: checkbox
      name: bike1
      attrs:
        - key: value
          value: Obstacle or hazard in path
    - prompt: Bike infrastructure needed
      type: checkbox
      name: bike2
      attrs:
        - key: value
          value: Bike infrastructure needed
    - prompt: Bike parking needed
      type: checkbox
      name: bike3
      attrs:
        - key: value
          value: Bike parking needed
    - prompt: Other
      type: checkbox
      name: bike4
      attrs:
        - key: value
          value: Other

    # public space
    - prompt: Greenspace here please
      type: checkbox
      name: publicspace1
      attrs:
        - key: value
          value: Greenspace here please
    - prompt: Community garden here would be nice
      type: checkbox
      name: publicspace2
      attrs:
        - key: value
          value: Community garden here would be nice
    - prompt: More street trees
      type: checkbox
      name: publicspace3
      attrs:
        - key: value
          value: More street trees
    - prompt: Area does not feel safe or is unattractive
      type: checkbox
      name: publicspace4
      attrs:
        - key: value
          value: Area does not feel safe or is unattractive
    - prompt: Other
      type: checkbox
      name: publicspace5
      attrs:
        - key: value
          value: Other
          
    # other info
    - prompt: Share more details
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Give us a brief description of the problem or place.      
    - prompt: _(Show us with a picture)
      inputfile_label: _(Upload an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: Your email (will be kept private)
      type: text
      name: private-email
      attrs:
        - key: size
          value: 30
    - prompt: How do you typically get around for most trips? (will be kept private)
      type: text
      name: private-mode
      attrs:
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    # start_page: true

  - title: _(Why Shareabouts?)
    slug: why
    url: /static/pages/why.html

  - title: _(Features)
    slug: features
    url: /static/pages/features.html

  - title: _(Links)
    pages:
      - title: _(Documentation)
        external: true
        url: https://github.com/openplans/shareabouts/tree/master/doc
      - title: _(Issues)
        external: true
        url: https://github.com/openplans/shareabouts/issues
      - title: _(GitHub)
        external: true
        url: https://github.com/openplans/shareabouts

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email